-- 15.	Identify the top 5 doctors who generated the most revenue but had the fewest patients. (SQL)
SELECT `Doctor Name` AS Doctor,
     SUM(`Total Bill`) AS Revenue,
    COUNT(DISTINCT patient_id) AS no_of_patients
FROM doctor_patients
GROUP BY Doctor
ORDER BY  Revenue DESC , no_of_patients 
LIMIT 5;

-- 16.	Find the department where the average waiting time has decreased over three consecutive months. (SQL)
WITH AvgWaitTimeByMonth AS (
    SELECT department_referral, `date`,ROUND(AVG(patient_waittime), 2) AS AvgWaitTime
    FROM hospital
    GROUP BY department_referral, `date`),
WaitTimeWithLag AS (
    SELECT department_referral,`date`, AvgWaitTime,
        LAG(AvgWaitTime, 1) OVER (PARTITION BY department_referral ORDER BY `date`) AS PrevMonthAvg,
        LAG(AvgWaitTime, 2) OVER (PARTITION BY department_referral ORDER BY `date`) AS TwoMonthsAgoAvg,
        LAG(AvgWaitTime, 3) OVER (PARTITION BY department_referral ORDER BY `date`) AS ThreeMonthsAgoAvg
    FROM AvgWaitTimeByMonth)
SELECT department_referral
FROM WaitTimeWithLag
WHERE AvgWaitTime < PrevMonthAvg
    AND PrevMonthAvg < TwoMonthsAgoAvg
    AND TwoMonthsAgoAvg < ThreeMonthsAgoAvg
GROUP BY department_referral;

-- 17.	Determine the ratio of male to female patients for each doctor and rank the doctors based on this ratio. (SQL)
WITH patientCount AS (
	SELECT d.`Doctor Name` AS Doctor_Name,
        SUM(CASE WHEN h.patient_gender = "M" THEN 1 ELSE 0 END) AS male_count,
        SUM(CASE WHEN h.patient_gender = "F" THEN 1 ELSE 0 END) AS female_count
	FROM hospital AS h 
	JOIN doctor_patients AS d ON h.patient_id = d.patient_id
	GROUP BY Doctor_Name),
DoctorRatios AS (SELECT Doctor_Name,male_count,female_count,
        ROUND((male_count / female_count), 2) AS Male_To_Female_ratio
	FROM patientCount)
SELECT Doctor_Name,male_count,female_count,Male_To_Female_ratio,
    DENSE_RANK() OVER (ORDER BY Male_To_Female_ratio DESC) AS Ranking 
FROM DoctorRatios;


-- 18.	Calculate the average satisfaction score of patients for each doctor based on their visits. (SQL)
SELECT d.`Doctor Name` AS Doctor_Name,
    ROUND(AVG(CASE WHEN h.patient_sat_score = "" THEN 5 ELSE h.patient_sat_score END), 2) AS patient_sat_score
FROM hospital AS h 
JOIN doctor_patients AS d 
    ON h.patient_id = d.patient_id
GROUP BY Doctor_Name
ORDER BY patient_sat_score DESC;


-- 19.	Find doctors who have treated patients from different races and calculate the diversity of their patient base. (SQL)
SELECT d.`Doctor Name` AS Doctor_Name,
    COUNT(DISTINCT h.patient_race) AS differnet_race_count
FROM hospital AS h 
JOIN doctor_patients AS d
    ON h.patient_id = d.patient_id
GROUP BY Doctor_Name
HAVING COUNT(DISTINCT h.patient_race) > 1
ORDER BY differnet_race_count DESC;


-- 20.	Calculate the ratio of total bills generated by male patients to female patients for each department. (SQL)
SELECT h.department_referral,
    SUM(CASE WHEN patient_gender = "M" THEN d.`Total Bill` END) AS Male_total_bill,
    SUM(CASE WHEN patient_gender = "F" THEN d.`Total Bill` END) AS Female_total_bill,
    ROUND(
        SUM(CASE WHEN patient_gender = "M" THEN d.`Total Bill` END) / 
        SUM(CASE WHEN patient_gender = "F" THEN d.`Total Bill` END), 2) AS Male_To_Female_Ratio
FROM hospital AS h 
JOIN doctor_patients AS d
    ON h.patient_id = d.patient_id
GROUP BY h.department_referral;


-- 21.	Update the patient satisfaction score for all patients who visited the "General Practice" department and 
-- had a waiting time of more than 30 minutes. Increase their satisfaction score by 2 points, but ensure that 
-- the satisfaction score does not exceed 10. (SQL)
UPDATE hospital
SET patient_sat_score = LEAST(patient_sat_score + 2,10)
WHERE LOWER(department_referral) = "general practice" AND patient_waittime > 30;

